### ISSUE TITLE
Hash in routes

### ISSUE THREAD

**Issue by jcristovao** [MartinKolarik/ractive-route#3]
Would it be possible to add hash support to routes, so that we can have something like:

    router.addRoute('#dashboard/:item', ItemFunction);

Instead of the (currently) mandatory:

    router.addRoute('/dashboard/:item', ItemFunction);

Or is this already possible and I'm missing something?
Thanks!

**Comment by MartinKolarik** [comment]
Do you need this because you need to support browsers that don't have the history API, or is there another use-case?

**Comment by jcristovao** [comment]
I admit to being a bit of a rookie here, I am yet to fully familiarize myself with client side routes, thus forgive me if I'm under some wrong assumption here, but here it goes:

I'm currently using modern browsers, and navigation goes as expected when clicking on links.

However, if I take one route and copy-paste it into a diferent browser window, as this route is not mapped in the nodejs/express side, it gives me a 404 (and I would expect some users to do this)

On the other hand, I was expecting a ```#something/something``` route to be fully copy-paste proof, in the sense that it would open the base page, which would then load the javascript (router included) and do the appropriate routing.

Is this a bad assumption? 

Thanks

**Comment by MartinKolarik** [comment]
Ah, I see. Your assumption is definitely correct. The page should load correctly when you reload the page, copy-paste a link, ...

It's also true that using `hash` as opposed to `path` would solve this problem, but it doesn't mean you can't get *both* - nice URLs and copy-pasteable links. This is more of a server-side issue.

In an ideal world, both the server and the client would know about all your routes. I.e. you'd either have to declare them twice, or use some format they both understand. Extending this project so that you get routing on both client and server is on my to-do list. In theory, ractive-route uses a format similar to express.js, so if your back-end is in JS, you might be able to reuse the routes.

Fortunately, your server probably doesn't really need to understand the routes. It just needs to respond with the correct file. Take a look at [this project](https://github.com/jsdelivr/beta.jsdelivr.com/blob/master/app.js). Basically, the server always responds with the `app.html` file, and routing is done on the client. There's also some UA sniffing involved, to pre-render pages for bots, not sure if you need that.

**Comment by jcristovao** [comment]
Thanks for your answer :)
Well, for now the link you provided was enough for it not to give me a 404. As I am using a static (express) server with subfolders it is not that easy (I don't go to the original page, but to the base page, using a redirect), but for now that's good enough.
Thus, you are totally right, some server support is always necessary.

However, perhaps I could then redirect to ```folder#/old/path```, and thus pass the path down to the client as... an hash? Would the (optional) `hash` implementation be something too dificult to implement?

Thanks

**Comment by MartinKolarik** [comment]
You can change

```js
app.all('/*', function (req, res) {
	res.sendFile(__dirname + '/views/app.html');
});
```

to something like

```js
app.all('/folder/*', function (req, res) {
	res.sendFile(__dirname + '/views/app.html');
});
```

if you want to catch only requests under `/folder/`, doesn't that solve your problem?

ractive-route uses the `hash` so store data, so it'd require some changes to make this work, if you really need this, I think there's a better way. I suppose you currently do something like this to perform the initial `dispatch()`:

```js
router.init();
```

Instead, you can parse the `hash` yourself, and perform the `dispatch()` manually:

```js
// You might need to use some decoding/encoding here, but...
router.dispatch(location.hash.substr(2), { noHistory: true });
```

**Comment by jcristovao** [comment]
> Instead, you can parse the hash yourself, and perform the dispatch() manually:

Thank you very much! I think that does the trick, I'll do some more tests and if everything goes well I'll close this :)
